# -*- coding: utf-8 -*-
"""Aulas EBAC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2jmtmFnlFg8McAOCAQcG2QIuq25CtSy

Minha primeira calculadora
"""

print("=== Calculadora do Diego ===")

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))

print("Escolha a operação:")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

op = input("Digite o número da operação: ")

if op == "1":
    print("Resultado:", n1 + n2)

elif op == "2":
    print("Resultado:", n1 - n2)

elif op == "3":
    print("Resultado:", n1 * n2)

elif op == "4":
    if n2 != 0:
        print("Resultado:", n1 / n2)
    else:
        print("Não é possível dividir por zero")

else:
    print("Operação inválida")

print ('olá mundo')



"""Operadores Aritmétricos"""

# Adição
10+2
# Subtração
5 - 2

# Multriplicação
5 * 2

# Resto da divisão
5 % 2

# Potenciação
5**2

# Divisão
5 / 2

# Divisão Inteira
 5 // 2

"""Operadores Relacionais

"""

# Menor
1<2
# Menor ou igual
1<=10
# Maior
2>1
# Mario ou igual
2>=2
#Igual
5==5
Diferente
5!=8

y = 10; x = 8
soma = x + y
print (soma)

nome = input("Digite o nome do usuário ") # Aguarda o usuário digital algo
print (nome)

x = 5
print('o valor de x é', x)

# if
if 5 < 10:
  print("Verdade")

# If/Else
num1 = 11
num2 = 11
if num1 > num2:
  print("o num1 é maior número")
elif num1 < num2:
  print("O num2 é o maior número")
else:
  print("O dois são iguais")

# For Range
for contador in range(10):
  print(contador)

# For Range + Break
for contador in range(1000):
  print(contador)
  if contador == 15:
    break

lista2 = [2,3,4]

for val in lista2:
    val *=2
    print(val)

# While com else
val = 1
while (val < 6):
    val *= 2
    print(val)

else:
    print('Valor de val é:',val)

# solicita o nome do usuário e o exibe
nome_usuario = input('Digite o seu nome: ')
print(f"Olá, {nome_usuario}! Bem-vindo ao nosso sistema.")

# Solicita a idade do usuário e converte para inteiro
idade_usuario = int(input('Digite a sua idade: '))
#verifica se o usuário é maior de idade
if idade_usuario >= 18:
    print('Você é maior de idade.')
else:
    print('Você é menor de idade.')